# 发送邮件请求
POST http://{{address}}/
Content-Type: application/json

{
    "email": {
        "to": ["1149062639@qq.com"],
        "subject": "给你看就是那个富士康的！！！",
        "content": "了但考虑？？？？"
    },
    "sendOptions": {
        "async": false,
        "timeout": 3000
    }
}

###